name: Publish to PyPI.org
on: workflow_dispatch
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt
      - name: Build package
        run: python -m build
      - run: python3 -m pip install --upgrade build && python3 -m build